#include <core/Helpers/Xml.h>
#include <core/Basics/Drumkit.h>
#include <core/Basics/DrumkitComponent.h>
#include <core/Basics/Instrument.h>
#include <core/Basics/InstrumentComponent.h>
#include <core/Basics/InstrumentLayer.h>
#include <core/Basics/InstrumentList.h>
#include <core/Basics/Sample.h>
#include <core/Preferences.h>
#include <core/Basics/Pattern.h>
#include <core/Basics/PatternList.h>
#include <core/Basics/AutomationPath.h>
#include <core/Basics/Song.h>
#include <core/Hydrogen.h>
#include <qtreset.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <custom_qt_casters.h>
